@startuml (id=JuvalLowy)

' Псевдонимы
' #7FFFD4\#AFEEEE - Actors
' #A6CE39 - Clients
' #FFF200 - Managers
' #FFCB05 - Engines
' #BCBEC0 - Resource Access
' #74CEE2 - Resources
' #DD9DC6 - Utils
' DarkKhaki - Data
' LightGoldenrodYellow - New Modules
' Honeydew - Temporary Modules

!$ActorOneColor        = "#7FFFD4"
!$ActorTwoColor        = "#AFEEEE"
!$UserColor            = "#3F48CC"
!$ClientColor          = "#A6CE39"
!$FrontColor           = "#A6CE39"
!$ManagerColor         = "#FFF200"
!$EngineColor          = "#FFCB05"
!$ResourceAccessColor  = "#BCBEC0"
!$ResourcesColor       = "#74CEE2"
!$UtilityColor         = "#DD9DC6"
!$DataColor            = "#BDB76B"
!$NewModuleColor       = "#FAFAD2"
!$TemporaryModuleColor = "#F0FFF0"
!$BoundaryColor        = "#AFEEEE"
!$AltColor             = "#FFFFE0"
!$AltElseColor         = "#FFDAB9"
!$NoteColor            = "#B0C4DE"

' Сделать картинку, которая дает понимания по цветам
' Каждая роль в виде компонентной диаграммы
' Назвать файл как-нить Инструкции
' [Colors]

!unquoted procedure AddLegend($userVaule)
legend center
| **Цвет** | **Пометка** | **Расшифровка** | **Значение** |
|<$UserColor>| User | Пользователь приложения | $userVaule |
|<$FrontColor>| Front | Фронт приложение| Веб- или мобильное приложение, система, внешний сервис |
|<$UtilityColor>| Infrastructure | Инфраструктурное приложение | Инфраструктурная улитита, сервис или служба |
|<$ManagerColor>| Orchestrator | Оркестратор бизнес-процесса | Cервис, реализующий некоторые логически связанные бизнес-процессы |
|<$ResourceAccessColor>| Resource Access | Доступ к ресурсу системы | Сервис, инкапсулирующий работу с ресурсами |
|<$DataColor>| Data | Данные системы | Внутренние ресурсы системы |
|<$BoundaryColor>| Boundary | Cистемная граница / Программный элемент в системе | Элементы пользовательского интерфейса |
|<$TemporaryModuleColor>| Temporary Module | Временный модуль системы | Модуль системы, от которого планируется отказаться |
|<$NewModuleColor>| New Module | Новый модуль системы | Модуль системы, который планируется разработать  |
end legend
!endprocedure

@enduml
